{% set version = "0.1.x" %}

package:
  name: xpdan
  version: {{ version }}

source:
  url: https://github.com/xpdacq/xpdan/archive/v{{ version }}.tar.gz
  fn: xpdan-v{{ version }}.tar.gz

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - numpy
    - matplotlib

test:
  imports:
    - xpdan
